# Profitable App Profiles for the App Store and Google Play Markets

### Opening the datasets

We will be looking at datasets containing data about Androit apps from Google Play and iOS apps from App Store:
* A dataset containing data about approximately 10,000 Android apps from Google Play; the data was collected in August 2018.

* A dataset containing data about approximately 7,000 iOS apps from the App Store; the data was collected in July 2017.

We first open the files and extract headers to find the names of columns in each dataset.

In [1]:
from csv import reader

def open_data_and_get_header(file_name):
    open_file = open(file_name)
    read_file = reader(open_file)
    dataset = list(read_file)
    header = dataset[0]
    dataset = dataset[1:]
    print(header, '\n')
    return dataset
    

Next we will open the datasets and explore their contents

In [2]:
def explore_data(dataset, start, end, rows_and_columns=False):
    dataset_slice = dataset[start:end]    
    for row in dataset_slice:
        print(row, '\n')

    if rows_and_columns:
        print('Number of rows:', len(dataset))
        print('Number of columns:', len(dataset[0]))

In [3]:
apple_dataset = open_data_and_get_header('AppleStore.csv')
exploring_apple = explore_data(apple_dataset, 0, 2, True)

['id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic'] 

['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1'] 

['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1'] 

Number of rows: 7197
Number of columns: 16


In [4]:
google_dataset = open_data_and_get_header('googleplaystore.csv')
exploring_google = explore_data(google_dataset, 0, 2, True)

['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver'] 

['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN', '4.1', '159', '19M', '10,000+', 'Free', '0', 'Everyone', 'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'] 

['Coloring book moana', 'ART_AND_DESIGN', '3.9', '967', '14M', '500,000+', 'Free', '0', 'Everyone', 'Art & Design;Pretend Play', 'January 15, 2018', '2.0.0', '4.0.3 and up'] 

Number of rows: 10841
Number of columns: 13


## Data Cleaning
### Removing Rows with Missing Column Entry

Before beginning our analysis, we need to make sure the data we analyze is accurate, or the results of our analysis will be wrong. This means that we need to:

* Detect inaccurate data, and correct or remove it;
* Detect duplicate data, and remove the duplicates.


Since we focus on apps designed for *English speaking* audience that are also *free*, we will be removing:
* non-English apps;
* apps that are not free.

First, lets find the errors in datasets. From a dedicated discussion section we know that there is an error in a certain row. Lets find this row:

In [5]:
def bad_data(dataset):
    for row in dataset[1:]:
        if len(row) != len(dataset[0]):
            print('Row missing a column: ', dataset.index(row))
            print()
            print('Length of irregular row:', 
                  len(dataset[dataset.index(row)]))
            print('Length of the dataset header:', len(dataset[0]))

In [6]:
print('Checking Google Play data:', '\n')
bad_android = bad_data(google_dataset)
print()
print('Checking App Store data:', '\n')
bad_apple = bad_data(apple_dataset)

Checking Google Play data: 

Row missing a column:  10472

Length of irregular row: 12
Length of the dataset header: 13

Checking App Store data: 



From the results we can see, that Google's data has an error, which is a missing column in row 10472.
We will go and remove this row from a dataset.

In [7]:
print(len(google_dataset))
del google_dataset[10472] #use this only once!!
print(len(google_dataset))

10841
10840


### Removing Duplicate Entries

In this step we will look for duplicate data.

In [8]:
def unique_and_duplicate(dataset):
    duplicate_apps = []
    unique_apps = []
    for row in dataset:
        name = row[0]
        if name in unique_apps:
            duplicate_apps.append(name)
        else:
            unique_apps.append(name)
    
    print('Number of duplicate apps:', len(duplicate_apps))
    print()
    return duplicate_apps


In [9]:
print('Google Play:')
dup_google = unique_and_duplicate(google_dataset)

print('App Store:')
dup_apple = unique_and_duplicate(apple_dataset)

Google Play:
Number of duplicate apps: 1181

App Store:
Number of duplicate apps: 0



From the results we can see that Google Play store has 1181 duplicate app entries.
Now we need to determine the criterion by which we will remove the duplicate data. First we will look at the list of duplicate apps and then we will print an app of our choosing to determine the criterion by which we will remove the duplicates.

In [10]:
print(dup_google[:10])

['Quick PDF Scanner + OCR FREE', 'Box', 'Google My Business', 'ZOOM Cloud Meetings', 'join.me - Simple Meetings', 'Box', 'Zenefits', 'Google Ads', 'Google My Business', 'Slack']


In [11]:
def dup_app_info(app_name):
    for app in google_dataset:
        name = app[0]
        if name == app_name:
            print(app, '\n')

In [12]:
print(dup_app_info('Box'))
print(dup_app_info('Google Ads'))

['Box', 'BUSINESS', '4.2', '159872', 'Varies with device', '10,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 31, 2018', 'Varies with device', 'Varies with device'] 

['Box', 'BUSINESS', '4.2', '159872', 'Varies with device', '10,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 31, 2018', 'Varies with device', 'Varies with device'] 

['Box', 'BUSINESS', '4.2', '159872', 'Varies with device', '10,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 31, 2018', 'Varies with device', 'Varies with device'] 

None
['Google Ads', 'BUSINESS', '4.3', '29313', '20M', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 30, 2018', '1.12.0', '4.0.3 and up'] 

['Google Ads', 'BUSINESS', '4.3', '29313', '20M', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 30, 2018', '1.12.0', '4.0.3 and up'] 

['Google Ads', 'BUSINESS', '4.3', '29331', '20M', '5,000,000+', 'Free', '0', 'Everyone', 'Business', 'July 30, 2018', '1.12.0', '4.0.3 and up'] 

None


After looking at duplicates, we can see that we can use a column `Reviews` at index position 3 as our criteria to remove duplicate apps.

To begin removing duplicates, we first add apps with the highest `Reviews` score into a new dictionary. Those apps that have the correct entry is put into the same dictionary too. We then check the length of dictionary to the expected length of the dataset to check if the dictionary is populated correctly.

In [13]:
reviews_max = {}

for row in google_dataset:
    name = row[0]
    n_reviews = float(row[3])
    
    if name in reviews_max and reviews_max[name] < n_reviews:
        reviews_max[name] = n_reviews
    elif name not in reviews_max:
        reviews_max[name] = n_reviews

print('Expected length:', len(google_dataset) - 1181)
print('Actual length:',len(reviews_max))

Expected length: 9659
Actual length: 9659


Now we will use the `reviews_max` dictionary we created to remove the duplicates from the dataset.
In the code cell below:
* We initialize two empty list;
* We loop through the `google_dataset` dataset:
    * For every iteration we isolate the name of the app and the number of reviews;
    * We add the current row to the `android_clean` list and the app name to the `already_added` list if:
        * The number of reviews of the current app matches the number of reviews of that app as described in the `reviews_max`;
        * The name of the app is not already in the `already_added` list. We need to add this supplementary condition to account for those cases where the highest number of reviews of a duplicate app is the same for more than one entry.

In [14]:
android_clean = []
already_added = []

for row in google_dataset:
    name = row[0]
    n_reviews = float(row[3])
    
    if (reviews_max[name] == n_reviews) and (name not in already_added):
        android_clean.append(row)
        already_added.append(name)
        
print('Expected length:', len(google_dataset) - 1181)
print('Actual length:', len(android_clean))
print()
print('Confirming info by reruning `explore_data` function:', '\n')
print(explore_data(android_clean, 0, 2, True))

Expected length: 9659
Actual length: 9659

Confirming info by reruning `explore_data` function: 

['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN', '4.1', '159', '19M', '10,000+', 'Free', '0', 'Everyone', 'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'] 

['U Launcher Lite – FREE Live Cool Themes, Hide Apps', 'ART_AND_DESIGN', '4.7', '87510', '8.7M', '5,000,000+', 'Free', '0', 'Everyone', 'Art & Design', 'August 1, 2018', '1.2.4', '4.0.3 and up'] 

Number of rows: 9659
Number of columns: 13
None


### Removing Non-English Apps

Now that we have removed the duplicate apps from our dataset, we need to check if there are any non-english apps and remove if there are any. We do so because we analyze apps that are designed for an English-speaking audience.
Some apps names contain emojis and other special characters, but they still are English. We are checking the names in accordance with ASCII range to determine if the name of the app is English. According to ASCII, the characters we commonly use in an English text corresponds to numbers in the range 0 to 127.

Some English app names use emojis or other symbols (™, — (em dash), – (en dash), etc.) that fall outside of the ASCII range. Because of this, we'll remove useful apps if we use the function in its current form.

In [15]:
def english_app(app_name):
    for character in app_name:
        if ord(character) > 127:
            return False
    
    return True

        
print(english_app('Instagram'))
print(english_app('爱奇艺PPS -《欢乐颂2》电视剧热播'))
print(english_app('Docs To Go™ Free Office Suite'))
print(english_app('Instachat 😜'))

True
False
False
False


To minimize the impact of data loss, we'll only remove an app if its name has more than three characters with corresponding numbers falling outside the ASCII range. This means all English apps with up to three emoji or other special characters will still be labeled as English.

In [16]:
def english_app(app_name):
    non_ascii = 0
    
    for character in app_name:
        if ord(character) > 127:
            non_ascii += 1
    
    if non_ascii > 3:
        return False
    else:
        return True
    
print(english_app('Instagram'))
print(english_app('爱奇艺PPS -《欢乐颂2》电视剧热播'))
print(english_app('Docs To Go™ Free Office Suite'))
print(english_app('Instachat 😜'))

True
False
True
True


In [17]:
android_english = []
apple_english = []

for row in android_clean:
    name = row[0]
    if english_app(name):
        android_english.append(row)
        
for row in apple_dataset:
    name = row[1]
    if english_app(name):
        apple_english.append(row)


explore_data(android_english, 0, 3, True)
print()
explore_data(apple_english, 0, 3, True)
print()

['Photo Editor & Candy Camera & Grid & ScrapBook', 'ART_AND_DESIGN', '4.1', '159', '19M', '10,000+', 'Free', '0', 'Everyone', 'Art & Design', 'January 7, 2018', '1.0.0', '4.0.3 and up'] 

['U Launcher Lite – FREE Live Cool Themes, Hide Apps', 'ART_AND_DESIGN', '4.7', '87510', '8.7M', '5,000,000+', 'Free', '0', 'Everyone', 'Art & Design', 'August 1, 2018', '1.2.4', '4.0.3 and up'] 

['Sketch - Draw & Paint', 'ART_AND_DESIGN', '4.5', '215644', '25M', '50,000,000+', 'Free', '0', 'Teen', 'Art & Design', 'June 8, 2018', 'Varies with device', '4.2 and up'] 

Number of rows: 9614
Number of columns: 13

['284882215', 'Facebook', '389879808', 'USD', '0.0', '2974676', '212', '3.5', '3.5', '95.0', '4+', 'Social Networking', '37', '1', '29', '1'] 

['389801252', 'Instagram', '113954816', 'USD', '0.0', '2161558', '1289', '4.5', '4.0', '10.23', '12+', 'Photo & Video', '37', '0', '29', '1'] 

['529479190', 'Clash of Clans', '116476928', 'USD', '0.0', '2130805', '579', '4.5', '4.5', '9.24.12', '9+', '

### Isolating the Free Apps

So far in the data cleaning process, we've done the following:
* Remove inaccurate data;
* Removed duplicate app entries;
* Removed non-English apps.

As we only build apps that are free to download and install, and our main source of revenue consists of in-app ads. Our datasets contain both free and non-free apps; we'll need to isolate only the free apps for our analysis.

In [18]:
free_android = []
free_apple = []

for row in android_english:
    price = row[6]
    if price == 'Free':
        free_android.append(row)
        
for row in apple_english:
    price = row[4]
    if price == '0.0':
        free_apple.append(row)
        
print('Number of free Android Apps:', len(free_android))
print()
print('Number of free Apple Apps:', len(free_apple))
print()

Number of free Android Apps: 8863

Number of free Apple Apps: 3222



## Data Analysis

### Most Common Apps by Genre

Our aim is to determine the kinds of apps that are likely to attract more users because our revenue is highly influenced by the number of people using our apps.

To minimize risks and overhead, our validation strategy for an app idea is comprised of three steps:

   * Build a minimal Android version of the app, and add it to Google Play.
   * If the app has a good response from users, we develop it further.
   * If the app is profitable after six months, we build an iOS version of the app and add it to the App Store.

Because our end goal is to add the app on both Google Play and the App Store, we need to find app profiles that are successful on both markets. For instance, a profile that works well for both markets might be a productivity app that makes use of gamification.

After inspecting the data sets to identify the columns that might be useful for determining the most common genres in each market, our conclusion was that we'll need to build a frequency table for the `prime_genre` column of the App Store data set, and for the `Genres` and `Category` columns of the Google Play data set.

We'll build two functions we can use to analyze the frequency tables:

   * One function to generate frequency tables that show percentages;
   * Another function we can use to display the percentages in a descending order.

We will use the built-in function `sorted()`.

In [19]:
def freq_table(dataset, index):
    frequency_table = {}
    total = 0
    
    for row in dataset:
        column = row[index]
        total += 1
        if column in frequency_table:
            frequency_table[column] += 1
        else:
            frequency_table[column] = 1
        
    freq_percentages = {}
    for key in frequency_table:
        percentage = (frequency_table[key] / total) * 100
        freq_percentages[key] = percentage

    return freq_percentages

def display_table(dataset, index):
    table = freq_table(dataset, index)
    table_display = []
    for key in table:
        key_val_as_tuple = (table[key], key)
        table_display.append(key_val_as_tuple)

    table_sorted = sorted(table_display, reverse = True)
    for entry in table_sorted:
        print(entry[1], ':', entry[0])

Generating frequency tables for selected columns `prime_genre`, `Genres` and `Category`:

In [20]:
print('Frequency table for Apple Apps by Genre:', '\n')
display_table(free_apple, -5) #prime_genre

Frequency table for Apple Apps by Genre: 

Games : 58.16263190564867
Entertainment : 7.883302296710118
Photo & Video : 4.9658597144630665
Education : 3.662321539416512
Social Networking : 3.2898820608317814
Shopping : 2.60707635009311
Utilities : 2.5139664804469275
Sports : 2.1415270018621975
Music : 2.0484171322160147
Health & Fitness : 2.0173805090006205
Productivity : 1.7380509000620732
Lifestyle : 1.5828677839851024
News : 1.3345747982619491
Travel : 1.2414649286157666
Finance : 1.1173184357541899
Weather : 0.8690254500310366
Food & Drink : 0.8069522036002483
Reference : 0.5586592178770949
Business : 0.5276225946617008
Book : 0.4345127250155183
Navigation : 0.186219739292365
Medical : 0.186219739292365
Catalogs : 0.12414649286157665


In [21]:
print('Frequency table for Google Play by Genre:', '\n')
display_table(free_android, 1) #Genres

Frequency table for Google Play by Genre: 

FAMILY : 18.898792733837304
GAME : 9.725826469592688
TOOLS : 8.462146000225657
BUSINESS : 4.592124562789123
LIFESTYLE : 3.9038700214374367
PRODUCTIVITY : 3.8925871601038025
FINANCE : 3.7007785174320205
MEDICAL : 3.5315355974275078
SPORTS : 3.396141261423897
PERSONALIZATION : 3.317161232088458
COMMUNICATION : 3.2381812027530184
HEALTH_AND_FITNESS : 3.0802211440821394
PHOTOGRAPHY : 2.944826808078529
NEWS_AND_MAGAZINES : 2.798149610741284
SOCIAL : 2.6627552747376737
TRAVEL_AND_LOCAL : 2.335552296062281
SHOPPING : 2.245289405393208
BOOKS_AND_REFERENCE : 2.1437436533904997
DATING : 1.8616721200496444
VIDEO_PLAYERS : 1.7939749520478394
MAPS_AND_NAVIGATION : 1.399074805370642
FOOD_AND_DRINK : 1.241114746699763
EDUCATION : 1.1621347173643235
ENTERTAINMENT : 0.9590432133589079
LIBRARIES_AND_DEMO : 0.9364774906916393
AUTO_AND_VEHICLES : 0.9251946293580051
HOUSE_AND_HOME : 0.8236488773552973
WEATHER : 0.8010831546880289
EVENTS : 0.7108202640189552
PAREN

In [22]:
print('Frequency table for Google Play by Category:', '\n')
display_table(free_android, -4) #Category

Frequency table for Google Play by Category: 

Tools : 8.450863138892023
Entertainment : 6.070179397495204
Education : 5.348076272142616
Business : 4.592124562789123
Productivity : 3.8925871601038025
Lifestyle : 3.8925871601038025
Finance : 3.7007785174320205
Medical : 3.5315355974275078
Sports : 3.463838429425702
Personalization : 3.317161232088458
Communication : 3.2381812027530184
Action : 3.102786866749408
Health & Fitness : 3.0802211440821394
Photography : 2.944826808078529
News & Magazines : 2.798149610741284
Social : 2.6627552747376737
Travel & Local : 2.324269434728647
Shopping : 2.245289405393208
Books & Reference : 2.1437436533904997
Simulation : 2.042197901387792
Dating : 1.8616721200496444
Arcade : 1.8503892587160102
Video Players & Editors : 1.771409229380571
Casual : 1.7601263680469368
Maps & Navigation : 1.399074805370642
Food & Drink : 1.241114746699763
Puzzle : 1.128286133363421
Racing : 0.9928917973598104
Role Playing : 0.9364774906916393
Libraries & Demo : 0.93647749

## Most Popular Apps by Genre on the App Store

In [28]:
freq_prime_genre = freq_table(free_apple, -5) #prime_genre

for genre in freq_prime_genre:
    total = 0
    len_genre = 0
    for app in free_apple:
        genre_app = app[-5]
        if genre_app == genre:
            n_ratings = float(app[5])
            total += n_ratings
            len_genre += 1
    avg_n_ratings = total / len_genre
    print(genre, ':', avg_n_ratings)

Social Networking : 71548.34905660378
Photo & Video : 28441.54375
Games : 22788.6696905016
Music : 57326.530303030304
Reference : 74942.11111111111
Health & Fitness : 23298.015384615384
Weather : 52279.892857142855
Utilities : 18684.456790123455
Travel : 28243.8
Shopping : 26919.690476190477
News : 21248.023255813954
Navigation : 86090.33333333333
Lifestyle : 16485.764705882353
Entertainment : 14029.830708661417
Food & Drink : 33333.92307692308
Sports : 23008.898550724636
Book : 39758.5
Finance : 31467.944444444445
Education : 7003.983050847458
Productivity : 21028.410714285714
Business : 7491.117647058823
Catalogs : 4004.0
Medical : 612.0


In [29]:
for app in free_apple:
    if app[-5] == 'Social Networking':
        print(app[1], ':', app[5]) # print name and number of ratings

Facebook : 2974676
Pinterest : 1061624
Skype for iPhone : 373519
Messenger : 351466
Tumblr : 334293
WhatsApp Messenger : 287589
Kik : 260965
ooVoo – Free Video Call, Text and Voice : 177501
TextNow - Unlimited Text + Calls : 164963
Viber Messenger – Text & Call : 164249
Followers - Social Analytics For Instagram : 112778
MeetMe - Chat and Meet New People : 97072
We Heart It - Fashion, wallpapers, quotes, tattoos : 90414
InsTrack for Instagram - Analytics Plus More : 85535
Tango - Free Video Call, Voice and Chat : 75412
LinkedIn : 71856
Match™ - #1 Dating App. : 60659
Skype for iPad : 60163
POF - Best Dating App for Conversations : 52642
Timehop : 49510
Find My Family, Friends & iPhone - Life360 Locator : 43877
Whisper - Share, Express, Meet : 39819
Hangouts : 36404
LINE PLAY - Your Avatar World : 34677
WeChat : 34584
Badoo - Meet New People, Chat, Socialize. : 34428
Followers + for Instagram - Follower Analytics : 28633
GroupMe : 28260
Marco Polo Video Walkie Talkie : 27662
Miitomo : 2

## Most Popular Apps by Genre on Google Play

In [33]:
freq_category = freq_table(free_android, -4) #Category

for category in freq_category:
    total = 0
    len_category = 0
    for app in free_android:
        category_app = app[-4]
        if category_app == category:
            n_installs = app[5]
            n_installs = n_installs.replace(',', '')
            n_installs = n_installs.replace('+', '')
            n_installs = float(n_installs)
            total += n_installs
            len_category += 1
    avg_n_installs = total / len_category
    print(category, ':', avg_n_installs)

Art & Design : 2122850.9433962265
Art & Design;Creativity : 285000.0
Auto & Vehicles : 647317.8170731707
Beauty : 513151.88679245283
Books & Reference : 8767811.894736841
Business : 1712290.1474201474
Comics : 831873.1481481482
Comics;Creativity : 50000.0
Communication : 38456119.167247385
Dating : 854028.8303030303
Education : 550185.4430379746
Education;Creativity : 2875000.0
Education;Education : 4759517.0
Education;Pretend Play : 1800000.0
Education;Brain Games : 5333333.333333333
Entertainment : 5602792.775092937
Entertainment;Brain Games : 3314285.714285714
Entertainment;Creativity : 4000000.0
Entertainment;Music & Video : 6413333.333333333
Events : 253542.22222222222
Finance : 1387692.475609756
Food & Drink : 1924897.7363636363
Health & Fitness : 4188821.9853479853
House & Home : 1331540.5616438356
Libraries & Demo : 638503.734939759
Lifestyle : 1412998.3449275363
Lifestyle;Pretend Play : 10000000.0
Card : 3815462.5
Arcade : 22888365.48780488
Puzzle : 8302861.91
Racing : 1591064

In [34]:
for app in free_android:
    if app[-4] == 'Art & Design':
        print(app[0], ':', app[5]) # print name and number of installs

Photo Editor & Candy Camera & Grid & ScrapBook : 10,000+
U Launcher Lite – FREE Live Cool Themes, Hide Apps : 5,000,000+
Sketch - Draw & Paint : 50,000,000+
Paper flowers instructions : 50,000+
Smoke Effect Photo Maker - Smoke Editor : 50,000+
Infinite Painter : 1,000,000+
Garden Coloring Book : 1,000,000+
Text on Photo - Fonteee : 1,000,000+
Name Art Photo Editor - Focus n Filters : 1,000,000+
Tattoo Name On My Photo Editor : 10,000,000+
Mandala Coloring Book : 100,000+
3D Color Pixel by Number - Sandbox Art Coloring : 100,000+
Learn To Draw Kawaii Characters : 5,000+
Photo Designer - Write your name with shapes : 500,000+
350 Diy Room Decor Ideas : 10,000+
FlipaClip - Cartoon animation : 5,000,000+
ibis Paint X : 10,000,000+
Logo Maker - Small Business : 100,000+
Boys Photo Editor - Six Pack & Men's Suit : 100,000+
Superheroes Wallpapers | 4K Backgrounds : 500,000+
HD Mickey Minnie Wallpapers : 50,000+
Harley Quinn wallpapers HD : 10,000+
Animated Photo Editor : 100,000+
Pencil Sketc

## Conclusions

In this project, we analyzed data about the App Store and Google Play mobile apps with the goal of recommending an app profile that can be profitable for both markets.

*We concluded that taking a popular book (perhaps a more recent book) and turning it into an app could be profitable for both the Google Play and the App Store markets. The markets are already full of libraries, so we need to add some special features besides the raw version of the book. This might include daily quotes from the book, an audio version of the book, quizzes on the book, a forum where people can discuss the book, etc.* (<--- needs changing!!)